'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sign

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''NoDocsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoDocsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''InstructionsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstructionsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TopInstructionsLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TopInstructionsLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ConfigDocDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfigDocDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SenderLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SenderRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SenderDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RecipientLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecipientRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RecipientDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''FormerRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormerRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SenderRecipientWarningRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderRecipientWarningRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SenderWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderWarning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''RecipientWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientWarning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SenderAddrLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderAddrLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SenderAddrRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderAddrRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SenderAddrDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderAddrDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RecipientAddrLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientAddrLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecipientAddrRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientAddrRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RecipientAddrDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientAddrDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SenderSignerLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderSignerLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SenderSignerRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderSignerRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SenderSignerDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderSignerDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RecipientSignerLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientSignerLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecipientSignerRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientSignerRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RecipientSignerDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientSignerDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SenderSignerWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SenderSignerWarning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''RecipientSignerWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientSignerWarning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DatesRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatesRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SignedOnRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignedOnRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SignedOnLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignedOnLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SignedOnRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignedOnRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ExpiresOnRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpiresOnRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ExpiresOnLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpiresOnLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExpiresOnRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpiresOnRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''SignRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignRS As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''LeftPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeftPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''SlidingZone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlidingZone1 As Global.Telerik.Web.UI.RadSlidingZone

    '''<summary>
    '''InstructionsRSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstructionsRSP As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''InstructionsLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstructionsLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''InstructionsLiteral1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstructionsLiteral1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''DataRSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataRSP As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''FirstItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''FirstItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FirstItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FirstInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FirstItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FirstItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''FirstItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FirstItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''FirstItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''SecondItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SecondItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SecondItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SecondInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SecondItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SecondItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SecondItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SecondItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''SecondItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''ThirdItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ThirdItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ThirdItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThirdInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ThirdItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ThirdItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ThirdItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ThirdItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ThirdItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirdItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''Fourthitemrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fourthitemrow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''FourthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FourthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FourthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FourthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FourthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''FourthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FourthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''FourthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''FifthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''FifthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FifthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FifthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FifthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FifthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''FifthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FifthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''FifthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''SixthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SixthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SixthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SixthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SixthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SixthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SixthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SixthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''SixthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SixthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''SeventhItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SeventhItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SeventhItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SeventhInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''SeventhItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SeventhItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SeventhItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SeventhItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''SeventhItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeventhItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''EighthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''EighthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''EighthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''EighthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''EighthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EighthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''EighthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''EighthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''EighthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EighthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''NinthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''NinthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''NinthitemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthitemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''NinthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''NinthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''NinthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''NinthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''NinthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''NinthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NinthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''TenthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TenthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TenthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TenthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TenthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''TenthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TenthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TenthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''TenthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TenthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''EleventhItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''EleventhItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''EleventhItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''EleventhInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''EleventhItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EleventhItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''EleventhItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''EleventhItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''EleventhItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EleventhItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''TwelfthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TwelfthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TwelfthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TwelfthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''TwelfthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''TwelfthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TwelfthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TwelfthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''TwelfthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TwelfthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''ThirteenthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ThirteenthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ThirteenthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThirteenthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ThirteenthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ThirteenthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ThirteenthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ThirteenthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ThirteenthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThirteenthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''FourteenthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''FourteenthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FourteenthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FourteenthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FourteenthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FourteenthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''FourteenthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FourteenthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''FourteenthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FourteenthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''FifteenthItemRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''FifteenthItemCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FifteenthItemLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FifteenthInputCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthInputCell As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''FifteenthItemRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FifteenthItemCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''FifteenthItemRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''FifteenthItemRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemRDP As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''FifteenthItemRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FifteenthItemRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''ShowDataRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowDataRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SignRSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignRSP As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''ctlSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlSignature As Global.SuperSignature.MouseSignature

    '''<summary>
    '''InitialsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InitialsTable As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ctlInitials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlInitials As Global.SuperSignature.MouseSignature

    '''<summary>
    '''ShowSigRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowSigRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''OtherRSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherRSP As Global.Telerik.Web.UI.RadSlidingPane

    '''<summary>
    '''OutsideDocsRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OutsideDocsRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''UploadTemplateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadTemplateButton As Global.FASTPORT.UI.ThemeButton

    '''<summary>
    '''UploadPDFButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadPDFButton As Global.FASTPORT.UI.ThemeButton

    '''<summary>
    '''Radsplitbar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Radsplitbar1 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''DocRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''DocPageRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocPageRS As Global.Telerik.Web.UI.RadSlider

    '''<summary>
    '''PrintRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PagePnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PagePnl As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DocPageRLV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocPageRLV As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''DocPageDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocPageDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Next1Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next1Button As Global.FASTPORT.UI.ThemeButton

    '''<summary>
    '''Next2Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next2Button As Global.FASTPORT.UI.ThemeButton

    '''<summary>
    '''Next3Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next3Button As Global.FASTPORT.UI.ThemeButton

    '''<summary>
    '''Next4Button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Next4Button As Global.FASTPORT.UI.ThemeButton

    '''<summary>
    '''RewindButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RewindButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''MessageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''DashboardButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DashboardButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HiddenTB_ExecutionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_ExecutionID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PartyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PartyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_Review As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PageTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_DocID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_DocID As Global.System.Web.UI.WebControls.TextBox
End Class
