'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SignUpFP

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''SignUpRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SignUpRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''RadiusRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''RadiusLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadiusRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ByCityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ByCityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CityRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CityRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SearchCountryRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchCountryRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadiusRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''EditWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''EditCurrentJobWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditCurrentJobWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''SaveWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''DOTDupRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOTDupRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''MCDupRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCDupRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''CarrierWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''PickCarrierWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''LogoImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''_Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _Menu1 As Global.FASTPORT.UI.MarketingMenu

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TruckerRPB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerRPB As Global.Telerik.Web.UI.RadPanelBar

    '''<summary>
    '''UserRPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserRPI As Global.Telerik.Web.UI.RadPanelItem

    '''<summary>
    '''EmailRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''MobileRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''EmailRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''MobileRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PasswordRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RetypePasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RetypePasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RetypePasswordRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RetypePasswordRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FillRecaptchaLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FillRecaptchaLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''recaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recaptcha As Global.Recaptcha.RecaptchaControl

    '''<summary>
    '''CaptchaDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaptchaDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TruckerRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CarrierRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ContactRPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactRPI As Global.Telerik.Web.UI.RadPanelItem

    '''<summary>
    '''NameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NameRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''HandleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HandleRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandleRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''DirectDialLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectDialLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DirectDialRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectDialRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''MobileLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MobileRTB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileRTB1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OtherPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OtherPhoneRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherPhoneRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''FaxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FaxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FaxRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FaxRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''EmailLabe1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailLabe1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmailRTB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailRTB1 As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CarrierRPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierRPI As Global.Telerik.Web.UI.RadPanelItem

    '''<summary>
    '''CarrierSearchLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierSearchLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PickCarrierRSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierRSB As Global.Telerik.Web.UI.RadSearchBox

    '''<summary>
    '''CarrierRSB_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierRSB_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PickCarrierRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''PickCarrierDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CarrierInfoLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierInfoLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierEditRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierEditRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CarrierDelRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierDelRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''DOTNumberLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOTNumberLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DOTNumberRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOTNumberRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''MCNumberLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCNumberLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MCNumberRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCNumberRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''CarrierNameLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierNameLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierNameRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierNameRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CarrierEmailLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierEmailLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierEmailRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierEmailRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''CarrierAddrLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierAddrLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierAddrRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierAddrRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CarrierPhoneLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierPhoneLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierPhoneRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierPhoneRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''CarrierZipRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierZipRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''CarrierFaxLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierFaxLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierFaxRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierFaxRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''CarrierCountryRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierCountryRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ContactLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''HiddenTB_HistoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistoryID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchPartyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchPartyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchFree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchFree As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchCityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchCityID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchRadius control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchRadius As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PartyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PartyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_MeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_MeID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_DriverID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_DriverID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_AddrID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_AddrID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_AddrZipID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_AddrZipID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PrefParentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PrefParentID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_MouseOverID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_MouseOverID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierAddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierAddr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierZipID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierZipID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierCitySTZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierCitySTZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierCountryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierCountryID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierDataStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierDataStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierAdminYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierAdminYesNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_WindowWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_WindowWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HistoryHoverID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistoryHoverID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HistoryID_ForExpRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistoryID_ForExpRTT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_ExperienceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_ExperienceID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PartyExperienceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PartyExperienceID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_Slider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_Slider As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_IncidentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_IncidentID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_InfoRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_InfoRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HistRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_ExpRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_ExpRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_IncidentsRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_IncidentsRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_Tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_Tab As Global.System.Web.UI.WebControls.TextBox
End Class
