'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''ViewSourceRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewSourceRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''JobFoundOnLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobFoundOnLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''JobFoundRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobFoundRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''JobFoundDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobFoundDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PostingCitiesLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostingCitiesLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PostingCitiesRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostingCitiesRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''PostingCitiesDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PostingCitiesDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SaveRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PrefRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''PrefRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''PrefDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''PointRW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PointRW As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''V_PartyOrgRecordControlCollapsibleRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents V_PartyOrgRecordControlCollapsibleRegion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''V_PartyOrgRecordControlPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents V_PartyOrgRecordControlPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''POILbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents POILbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactInfoLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactInfoLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ThumbsDownButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThumbsDownButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ThumbsUpButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThumbsUpButton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AmenitiesLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmenitiesLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PinsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PinsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PointStatsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PointStatsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HistoryLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HistoryLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ReviewsRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReviewsRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ReviewsDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReviewsDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''JobRadWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobRadWindow As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''LogoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''_Menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _Menu As Global.FASTPORT.UI.Menu

    '''<summary>
    '''_PageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _PageHeader As Global.FASTPORT.UI.Header

    '''<summary>
    '''MapSplitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MapSplitter As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''resultsPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resultsPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''DashboardRTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DashboardRTS As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''DashboardRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DashboardRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''DashboardDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DashboardDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''VerticalSplitBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerticalSplitBar As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''mapPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mapPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''JobDetailsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobDetailsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ViewDetailsRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewDetailsRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ApplyRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplyRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CloseRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''TruckerImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerImg As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''GaugeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GaugeImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TruckerInfoLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerInfoLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TruckerPaneRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerPaneRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''RightRSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RightRSB As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''RightRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RightRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''TruckerRPB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerRPB As Global.Telerik.Web.UI.RadPanelBar

    '''<summary>
    '''GeneralInstructionsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralInstructionsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmailRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''emailValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PasswordLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PasswordRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PasswordRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SearchMobileLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchMobileLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SearchMobileRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchMobileRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''NameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NameRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''SearchForTruckerRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchForTruckerRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PickTruckerRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickTruckerRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''PickTruckerDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickTruckerDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''HandleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HandleRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandleRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''TruckerTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TruckerTypeRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerTypeRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TruckerTypeDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerTypeDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''MobileLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MobileRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''DirectDialLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectDialLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DirectDialRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectDialRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''FaxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FaxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FaxRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FaxRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''SaveTruckerRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveTruckerRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''GaugeP1Img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GaugeP1Img As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''FastportP1RB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FastportP1RB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PrefsInstructionsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefsInstructionsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GaugeP2Img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GaugeP2Img As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''FastportP2RB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FastportP2RB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_GeneralLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_GeneralRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_GeneralDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_GeneralRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_EquipLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_EquipRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_EquipDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_EquipRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_CommodityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_CommodityRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_CommodityDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_CommodityRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_RegionsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_RegionsRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_RegionsDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_RegionsRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_OtherLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_OtherRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_OtherDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_OtherRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_EditRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EditRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RecordsInstructionsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecordsInstructionsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EstAccidentsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstAccidentsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EstAccidentsRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstAccidentsRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''IncidentsDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''EstTicketsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstTicketsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EstTicketsRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstTicketsRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''EstTestsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstTestsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EstTestsRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstTestsRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''EstFeloniesLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstFeloniesLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EstFeloniesRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EstFeloniesRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''HiddenTB_PartyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PartyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_TruckerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_TruckerID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_TopLeftLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_TopLeftLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_TopLeftLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_TopLeftLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_BottomRightLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_BottomRightLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_BottomRightLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_BottomRightLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_OriginLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_OriginLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_OriginLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_OriginLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_TabName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_TabName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CenterLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CenterLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CenterLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CenterLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PointID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PointID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HaveRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HaveRole As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_GaugeImageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_GaugeImageUrl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_RowIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_RowIndex As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchMobile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HeatMapData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HeatMapData As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_MapZoomLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_MapZoomLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PastLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PastLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PastLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PastLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_AdID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_AdID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PrefParentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PrefParentID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_MouseOverID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_MouseOverID As Global.System.Web.UI.WebControls.TextBox
End Class
