'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FastportConfig

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''InstRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''InfoRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InfoRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''InfoLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InfoLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PrefRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''PrefRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''PrefDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Col1RTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Col1RTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''GeneralRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''HiredRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiredRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''QuitRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuitRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''DOTDupRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOTDupRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''MCDupRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCDupRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''CarrierWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''PickCarrierWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''MilesWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MilesWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''ReasonLeftWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReasonLeftWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''UnemployedNotesWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnemployedNotesWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''EditWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''EditCurrentJobWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditCurrentJobWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''SaveWarningRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveWarningRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''RadiusRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''RadiusLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadiusRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ByCityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ByCityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CityRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CityRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''SearchCountryRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchCountryRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadiusRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadiusRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ExpRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRTT As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''ExpRTT_RG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRTT_RG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ExpRTT_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRTT_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ExperienceNotesRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExperienceNotesRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''ExpRTT_SaveCancelDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRTT_SaveCancelDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ExperienceNotesSaveRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExperienceNotesSaveRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ExperienceNotesCancelRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExperienceNotesCancelRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadWindowManager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager2 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''RadWindowDialogue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowDialogue As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''AddrRW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrRW As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''AddrLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddrRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''Addr2RTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Addr2RTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CitySTZipLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CitySTZipLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddrZipRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrZipRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''AddrCountryRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrCountryRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''CountryDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountryDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DatesAtLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatesAtLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MovedInLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MovedInLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MovedInRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MovedInRDP As Global.Telerik.Web.UI.RadMonthYearPicker

    '''<summary>
    '''MovedOutChkLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MovedOutChkLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MovedOutCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MovedOutCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MovedOutLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MovedOutLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MovedOutRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MovedOutRDP As Global.Telerik.Web.UI.RadMonthYearPicker

    '''<summary>
    '''AddrSaveRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrSaveRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''AddrCancelRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrCancelRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''JobRW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobRW As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''JobRTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobRTS As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''JobRMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobRMP As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''PageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageView1 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''PositionTypeLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PositionTypeLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PositionTypeRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PositionTypeRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''CurrentPastLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentPastLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CurrentPastRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CurrentPastRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''HiredLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiredLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HiredRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiredRDP As Global.Telerik.Web.UI.RadMonthYearPicker

    '''<summary>
    '''QuitLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuitLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuitRDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuitRDP As Global.Telerik.Web.UI.RadMonthYearPicker

    '''<summary>
    '''CarrierSearchLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierSearchLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PickCarrierRSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierRSB As Global.Telerik.Web.UI.RadSearchBox

    '''<summary>
    '''CarrierRSB_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierRSB_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PickCarrierRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''PickCarrierDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PickCarrierDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''CarrierInfoLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierInfoLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierEditRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierEditRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CarrierDelRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierDelRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''DOTNumberLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOTNumberLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DOTNumberRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOTNumberRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''MCNumberLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCNumberLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MCNumberRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCNumberRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''CarrierNameLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierNameLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierNameRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierNameRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CarrierEmailLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierEmailLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierEmailRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierEmailRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''CarrierAddrLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierAddrLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierAddrRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierAddrRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''CarrierPhoneLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierPhoneLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierPhoneRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierPhoneRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''CarrierZipRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierZipRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''CarrierFaxLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierFaxLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CarrierFaxRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierFaxRTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''CarrierCountryRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierCountryRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ContactLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ContactRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContactRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''UnemployedHeaderLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnemployedHeaderLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UnemployedNotesRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnemployedNotesRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''PageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageView2 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''MilesLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MilesLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MilesRTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MilesRTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''ReasonLeftLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReasonLeftLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ReasonLeftRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReasonLeftRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''ReasonLeftDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReasonLeftDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ReasonLeftNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReasonLeftNotes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ReasonLeftRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReasonLeftRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''CommVechLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommVechLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CommVechCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommVechCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DrugProgramLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrugProgramLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DrugProgramCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrugProgramCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageView3 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''EmploymentNoteLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmploymentNoteLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmploymentNotesRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmploymentNotesRE As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''StopVerifyLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StopVerifyLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GoVerifyLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoVerifyLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VerifyRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerifyRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FirstJobLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstJobLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FirstJobRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstJobRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''HistSaveRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HistSaveRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''HistCancelRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HistCancelRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''UnlockedLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnlockedLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LockedLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LockedLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LockRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LockRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''FastportRTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FastportRTS As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''ToDoRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDoRS As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ToDoItemsRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDoItemsRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''ToDoRPB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDoRPB As Global.Telerik.Web.UI.RadPanelBar

    '''<summary>
    '''GaugeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GaugeImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MenuRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''MenuDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''MustActRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MustActRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''MustActDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MustActDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''WaitingRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WaitingRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''WaitingDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WaitingDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ToDoRSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDoRSB As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''ToDoBodyRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToDoBodyRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''FPHeaderLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FPHeaderLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MiniProfileRadBinaryImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiniProfileRadBinaryImage As Global.Telerik.Web.UI.RadBinaryImage

    '''<summary>
    '''GeneralInstructionsLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralInstructionsLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''GenDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TruckerDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GetHelpRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetHelpRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ApplyRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplyRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''SendAppRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendAppRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''CarrierDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GetAppRD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GetAppRD As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''HiddenTB_ApplyURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_ApplyURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BasicFrameCollapsibleRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BasicFrameCollapsibleRegion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EmailTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''emailValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''DirectDialLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectDialLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DirectDialRadTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectDialRadTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''NameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NameTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''MobileLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MobileRadTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileRadTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''HandleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HandleTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HandleTB As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''OtherLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OtherRadTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherRadTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''TruckerTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TruckerTypeRCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerTypeRCB As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''TruckerTypeDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TruckerTypeDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''FaxLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FaxLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FaxRadTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FaxRadTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''NameRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''PersonalFrameCollapsibleRegion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PersonalFrameCollapsibleRegion1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DOBLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOBLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DOBRadTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOBRadTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''SSNLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SSNLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SSNRadTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SSNRadTB As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''USCitizenLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents USCitizenLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''USCitizenCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents USCitizenCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''AuthorizedAlienLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthorizedAlienLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AuthAlienCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthAlienCB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''AuthTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AuthTypeRadCombo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthTypeRadCombo As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''AuthTypeDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AuthTypeDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''VisaLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VisaLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VisaTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VisaTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PersonalRadButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PersonalRadButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''AddrFrameCollapsibleRegion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrFrameCollapsibleRegion2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''AddrSliderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrSliderLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AddrRadSlider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrRadSlider As Global.Telerik.Web.UI.RadSlider

    '''<summary>
    '''AddrAddRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrAddRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''AddrRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''AddrDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddrDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PrefsFrameCollapsibleRegion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrefsFrameCollapsibleRegion3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Pref_GeneralLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_GeneralRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_GeneralDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_GeneralRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_GeneralRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_EquipLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_EquipRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_EquipDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_EquipRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EquipRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_CommodityLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_CommodityRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_CommodityDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_CommodityRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_CommodityRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_RegionsLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_RegionsRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_RegionsDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_RegionsRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_RegionsRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_OtherLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Pref_OtherRAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherRAC As Global.Telerik.Web.UI.RadAutoCompleteBox

    '''<summary>
    '''Pref_OtherDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pref_OtherRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_OtherRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''Pref_EditRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pref_EditRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''YearsRadSlider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YearsRadSlider As Global.Telerik.Web.UI.RadSlider

    '''<summary>
    '''HistAddScratchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HistAddScratchButton As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''HistWarningLtl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HistWarningLtl As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''YrRLV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YrRLV As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''YrDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YrDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''R1Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R1Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''R1HistoryRLV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R1HistoryRLV As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''R1HistoryDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R1HistoryDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''R2HistoryRLV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R2HistoryRLV As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''R2HistoryDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R2HistoryDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''R3HistoryRLV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R3HistoryRLV As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''R3HistoryDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R3HistoryDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ExpRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRS As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''ExpTreeRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpTreeRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''ExpRSB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRSB As Global.Telerik.Web.UI.RadSearchBox

    '''<summary>
    '''ExpRTV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRTV As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''ExpRTV_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRTV_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''VerticalSplitBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VerticalSplitBar As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''ExpRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''DropExpImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropExpImg As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ExpUnlockedLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpUnlockedLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExpLockedLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpLockedLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExpLockRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpLockRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ExpRG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpRG As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ExpDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''IncidentsRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsRS As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''IncidentsTreeRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsTreeRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''IncidentsRTV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsRTV As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''IncidentsDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RadSplitBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitBar1 As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''IncidentsRP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsRP As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''DropIncidentImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropIncidentImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''IncidentUnlockedLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentUnlockedLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IncidentLockedLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentLockedLbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IncidentLockRB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentLockRB As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''AccidentsRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccidentsRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''AccidentsGridDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccidentsGridDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''IncidentsRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''IncidentsGridDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentsGridDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''HonorsAwardsRadGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HonorsAwardsRadGrid As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''HonorsAwardsDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HonorsAwardsDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''HiddenTB_PartyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PartyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_MeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_MeID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_DriverID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_DriverID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_AddrID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_AddrID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_AddrZipID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_AddrZipID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PrefParentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PrefParentID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_MouseOverID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_MouseOverID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HistoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistoryID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchPartyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchPartyID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchFree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchFree As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchCityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchCityID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_SearchRadius control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_SearchRadius As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierAddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierAddr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierZipID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierZipID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierCitySTZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierCitySTZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierCountryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierCountryID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierDataStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierDataStatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierLat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierLong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierLong As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_CarrierAdminYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_CarrierAdminYesNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_WindowWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_WindowWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HistoryHoverID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistoryHoverID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HistoryID_ForExpRTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistoryID_ForExpRTT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_ExperienceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_ExperienceID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_PartyExperienceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_PartyExperienceID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_Slider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_Slider As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_IncidentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_IncidentID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_InfoRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_InfoRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_HistRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_HistRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_ExpRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_ExpRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_IncidentsRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_IncidentsRun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenTB_Tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTB_Tab As Global.System.Web.UI.WebControls.TextBox
End Class
